2022-12-23 16:51:54,848 INFO    MainThread:23820 [internal.py:wandb_internal():90] W&B internal server running at pid: 23820, started at: 2022-12-23 16:51:54.848144
2022-12-23 16:51:54,849 INFO    WriterThread:23820 [datastore.py:open_for_write():75] open: F:\FYP\wandb\run-20221223_165154-cpkxc19b\run-cpkxc19b.wandb
2022-12-23 16:51:54,851 DEBUG   SenderThread:23820 [sender.py:send():236] send: header
2022-12-23 16:51:54,852 DEBUG   SenderThread:23820 [sender.py:send():236] send: run
2022-12-23 16:52:24,114 DEBUG   HandlerThread:23820 [handler.py:handle_request():140] handle_request: shutdown
2022-12-23 16:52:24,115 INFO    HandlerThread:23820 [handler.py:finish():806] shutting down handler
2022-12-23 16:52:24,145 INFO    WriterThread:23820 [datastore.py:close():279] close: F:\FYP\wandb\run-20221223_165154-cpkxc19b\run-cpkxc19b.wandb
2022-12-23 16:52:25,263 INFO    SenderThread:23820 [dir_watcher.py:__init__():216] watching files in: F:\FYP\wandb\run-20221223_165154-cpkxc19b\files
2022-12-23 16:52:25,263 INFO    SenderThread:23820 [sender.py:_start_run_threads():815] run started: cpkxc19b with start time 1671814314
2022-12-23 16:52:25,263 INFO    SenderThread:23820 [sender.py:finish():1114] shutting down sender
2022-12-23 16:52:25,263 INFO    SenderThread:23820 [dir_watcher.py:finish():353] shutting down directory watcher
2022-12-23 16:52:26,275 INFO    SenderThread:23820 [dir_watcher.py:finish():383] scan: F:\FYP\wandb\run-20221223_165154-cpkxc19b\files
2022-12-23 16:52:26,275 INFO    SenderThread:23820 [dir_watcher.py:finish():397] scan save: F:\FYP\wandb\run-20221223_165154-cpkxc19b\files\config.yaml config.yaml
2022-12-23 16:52:26,275 INFO    SenderThread:23820 [file_pusher.py:finish():171] shutting down file pusher
2022-12-23 16:52:26,276 INFO    SenderThread:23820 [file_pusher.py:join():176] waiting for file pusher
2022-12-23 16:52:40,218 ERROR   Thread-13 :23820 [internal_api.py:upload_file():1694] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/sevixdd/img2dataset/cpkxc19b/config.yaml?Expires=1671900746&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Hx5zRTO9sP1cdeWomgHkLP5woe7vPQnrEWs0EOtBQAt%2BOfrBn4ONR4hFkHbkdK6AE73q4p50LGHmeTAk4yBTSPGwanko1lHiKXAu2YGeErxMgM9YR1RyG4p4KJ2c1yAnI2WPUUQTpe3jwvvOyVTGMQ%2BVv8%2BEblgzbhv8hjRgEGmW1bIgwFgHdPWv3h0V%2BmikoL5weRwhjtdCN7Kp41RElSibcbw42TfZSvblnWzOZoIN8jkAvPRgl70%2BNPb7HC15qAKNQUYV8uJtD9ygyShmpQH4TAreg6QpvwwVhAAcDsmVLrxqD%2FBEqiHi%2F3yxvmIXeN8mmL5c6RRypXQuUaKCLA%3D%3D: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-12-23 16:52:40,218 ERROR   Thread-13 :23820 [internal_api.py:upload_file():1696] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2178'}
2022-12-23 16:52:40,219 ERROR   Thread-13 :23820 [internal_api.py:upload_file():1698] upload_file response body: 
2022-12-23 16:53:07,102 ERROR   Thread-13 :23820 [internal_api.py:upload_file():1694] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/sevixdd/img2dataset/cpkxc19b/config.yaml?Expires=1671900746&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Hx5zRTO9sP1cdeWomgHkLP5woe7vPQnrEWs0EOtBQAt%2BOfrBn4ONR4hFkHbkdK6AE73q4p50LGHmeTAk4yBTSPGwanko1lHiKXAu2YGeErxMgM9YR1RyG4p4KJ2c1yAnI2WPUUQTpe3jwvvOyVTGMQ%2BVv8%2BEblgzbhv8hjRgEGmW1bIgwFgHdPWv3h0V%2BmikoL5weRwhjtdCN7Kp41RElSibcbw42TfZSvblnWzOZoIN8jkAvPRgl70%2BNPb7HC15qAKNQUYV8uJtD9ygyShmpQH4TAreg6QpvwwVhAAcDsmVLrxqD%2FBEqiHi%2F3yxvmIXeN8mmL5c6RRypXQuUaKCLA%3D%3D: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-12-23 16:53:07,102 ERROR   Thread-13 :23820 [internal_api.py:upload_file():1696] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2178'}
2022-12-23 16:53:07,103 ERROR   Thread-13 :23820 [internal_api.py:upload_file():1698] upload_file response body: 
2022-12-23 16:53:10,494 INFO    Thread-13 :23820 [upload_job.py:push():138] Uploaded file F:\FYP\wandb\run-20221223_165154-cpkxc19b\files\config.yaml
2022-12-23 16:53:13,911 INFO    MainThread:23820 [internal.py:handle_exit():80] Internal process exited
