2022-12-23 16:47:19,154 INFO    MainThread:13528 [wandb_setup.py:_flush():76] Configure stats pid to 13528
2022-12-23 16:47:19,154 INFO    MainThread:13528 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Sevi\.config\wandb\settings
2022-12-23 16:47:19,154 INFO    MainThread:13528 [wandb_setup.py:_flush():76] Loading settings from F:\FYP\wandb\settings
2022-12-23 16:47:19,154 INFO    MainThread:13528 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-12-23 16:47:19,154 INFO    MainThread:13528 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'downloader.py', 'program': 'F:\\FYP\\downloader.py'}
2022-12-23 16:47:19,154 INFO    MainThread:13528 [wandb_setup.py:_flush():76] Applying login settings: {'anonymous': 'allow'}
2022-12-23 16:47:19,154 INFO    MainThread:13528 [wandb_init.py:_log_setup():461] Logging user logs to F:\FYP\wandb\run-20221223_164719-zph1jda3\logs\debug.log
2022-12-23 16:47:19,155 INFO    MainThread:13528 [wandb_init.py:_log_setup():462] Logging internal logs to F:\FYP\wandb\run-20221223_164719-zph1jda3\logs\debug-internal.log
2022-12-23 16:47:19,155 INFO    MainThread:13528 [wandb_init.py:init():495] calling init triggers
2022-12-23 16:47:19,155 INFO    MainThread:13528 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {'url_list': 'cc3m.tsv', 'image_size': 256, 'output_folder': 'F:\\datasets', 'processes_count': 16, 'resize_mode': 'border', 'resize_only_if_bigger': False, 'upscale_interpolation': 'lanczos', 'downscale_interpolation': 'area', 'encode_quality': 95, 'encode_format': 'jpg', 'skip_reencode': False, 'output_format': 'webdataset', 'input_format': 'tsv', 'url_col': 'URL', 'caption_col': 'caption', 'bbox_col': None, 'thread_count': 64, 'number_sample_per_shard': 10000, 'extract_exif': True, 'save_additional_columns': None, 'timeout': 10, 'enable_wandb': True, 'wandb_project': 'img2dataset', 'oom_shard_count': 5, 'compute_hash': 'sha256', 'distributor': 'multiprocessing', 'downloader': 'normal', 'subjob_size': 1000, 'retries': 0, 'disable_all_reencoding': False, 'min_image_size': 0, 'max_image_area': inf, 'max_aspect_ratio': inf, 'incremental_mode': 'incremental', 'max_shard_retry': 1, 'user_agent_token': None, 'disallowed_header_directives': ['noai', 'noimageai', 'noindex', 'noimageindex']}
2022-12-23 16:47:19,155 INFO    MainThread:13528 [wandb_init.py:init():548] starting backend
2022-12-23 16:47:19,155 INFO    MainThread:13528 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-12-23 16:47:19,157 INFO    MainThread:13528 [backend.py:ensure_launched():217] starting backend process...
2022-12-23 16:47:19,220 INFO    MainThread:13528 [backend.py:ensure_launched():222] started backend process with pid: 19760
2022-12-23 16:47:19,221 INFO    MainThread:13528 [wandb_init.py:init():558] backend started and connected
2022-12-23 16:47:19,240 INFO    MainThread:13528 [wandb_init.py:init():634] updated telemetry
2022-12-23 16:47:19,241 INFO    MainThread:13528 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-12-23 16:47:20,237 INFO    MainThread:13528 [wandb_run.py:_on_init():1919] communicating current version
2022-12-23 16:47:20,336 INFO    MainThread:13528 [wandb_run.py:_on_init():1923] got version response upgrade_message: "wandb version 0.13.7 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-12-23 16:47:20,336 INFO    MainThread:13528 [wandb_init.py:init():700] starting run threads in backend
2022-12-23 16:47:20,393 INFO    MainThread:13528 [wandb_run.py:_console_start():1893] atexit reg
2022-12-23 16:47:20,394 INFO    MainThread:13528 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.WRAP
2022-12-23 16:47:20,394 INFO    MainThread:13528 [wandb_run.py:_redirect():1803] Wrapping output streams.
2022-12-23 16:47:20,395 INFO    MainThread:13528 [wandb_run.py:_redirect():1827] Redirects installed.
2022-12-23 16:47:20,395 INFO    MainThread:13528 [wandb_init.py:init():732] run started, returning control to user process
2022-12-23 16:47:20,505 INFO    MainThread:13528 [wandb_run.py:_finish():1680] finishing run sevixdd/img2dataset/zph1jda3
2022-12-23 16:47:20,505 INFO    MainThread:13528 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-12-23 16:47:20,506 INFO    MainThread:13528 [wandb_run.py:_restore():1834] restore
2022-12-23 16:47:21,406 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 537
  total_bytes: 537
}

2022-12-23 16:47:21,716 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 537
  total_bytes: 537
}

2022-12-23 16:47:22,263 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 537
  total_bytes: 4044
}

2022-12-23 16:47:22,368 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 537
  total_bytes: 4070
}

2022-12-23 16:47:22,481 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 537
  total_bytes: 4070
}

2022-12-23 16:47:22,590 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4070
  total_bytes: 4070
}

2022-12-23 16:47:22,698 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4070
  total_bytes: 4070
}

2022-12-23 16:47:22,811 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4070
  total_bytes: 4070
}

2022-12-23 16:47:22,920 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4070
  total_bytes: 4070
}

2022-12-23 16:47:23,030 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4070
  total_bytes: 4070
}

2022-12-23 16:47:23,326 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4070
  total_bytes: 4070
}

2022-12-23 16:47:23,798 INFO    MainThread:13528 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4070
  total_bytes: 4070
}
local_info {
}

2022-12-23 16:47:24,916 INFO    MainThread:13528 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-12-23 16:47:24,916 INFO    MainThread:13528 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-12-23 16:47:24,918 INFO    MainThread:13528 [wandb_run.py:_footer_sync_info():3055] logging synced files
